### PR TITLE
Attempting to fix baseurl

### PR DESCRIPTION
**Pull request by ha6000**
This might not be the ideal change but this is what I got.

### CODE REVIEW

**Comment by ha6000** [comment]
Issue #332

**Comment by wictornogueira** [comment]
I was about to open a pull request and suddenly came across this one.
Would be nice if they merge this one... Really don't know why they didn't do so already.

**Comment by ha6000** [comment]
> I was about to open a pull request and suddenly came across this one.
> Would be nice if they merge this one... Really don't know why they didn't do so already.

I believe the maintainers are very busy at the moment

**Comment by 3846masa** [comment]
Sorry for the delay in response.
This issue has been resolved with the release of v2.0.0.

If you think this issue is still unresolved, please reopen it.

**Pull request closed without merging**
